# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbh < Formula
  desc "DB Harness project initializer"
  homepage "https://github.com/genesisdayrit/dbharness"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/genesisdayrit/dbharness/releases/download/v0.2.0/dbh_0.2.0_darwin_amd64.tar.gz"
      sha256 "dc6eb3ac0be3df509f413e695608d2673239bed6dd3d9b479a66eb6a8caec6b0"

      def install
        bin.install "dbh"
      end
    end
    on_arm do
      url "https://github.com/genesisdayrit/dbharness/releases/download/v0.2.0/dbh_0.2.0_darwin_arm64.tar.gz"
      sha256 "4ba4171bd5388c081b126d521fe693ba86609e73171f766f9c6bf079414c68c1"

      def install
        bin.install "dbh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/genesisdayrit/dbharness/releases/download/v0.2.0/dbh_0.2.0_linux_amd64.tar.gz"
        sha256 "c5d85db89e2316f3e9eb86e12614179972130c9c162528dd41d36bd558529fa3"

        def install
          bin.install "dbh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/genesisdayrit/dbharness/releases/download/v0.2.0/dbh_0.2.0_linux_arm64.tar.gz"
        sha256 "c44ee0eb010bdb24c407d1957a0bab12fce29e74a5f901edb12478dbbc2ecbb1"

        def install
          bin.install "dbh"
        end
      end
    end
  end

  test do
    system "#{bin}/dbh", "init", "--help"
  end
end
