# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbh < Formula
  desc "DB Harness project initializer"
  homepage "https://github.com/genesisdayrit/dbharness"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/genesisdayrit/dbharness/releases/download/v0.4.0/dbh_0.4.0_darwin_amd64.tar.gz"
      sha256 "6eb249fa0a47536558d6e3282b9359efab86387b99d26531daa940c4bf844f43"

      def install
        bin.install "dbh"
      end
    end
    on_arm do
      url "https://github.com/genesisdayrit/dbharness/releases/download/v0.4.0/dbh_0.4.0_darwin_arm64.tar.gz"
      sha256 "3eb91cc2c094989ce25cd1f6252eb6fe47a984877d140a82610baa67adc80769"

      def install
        bin.install "dbh"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/genesisdayrit/dbharness/releases/download/v0.4.0/dbh_0.4.0_linux_amd64.tar.gz"
        sha256 "9cdf82cd7441ecaa595ffd301cab70c50c5a448cbefb04ea55301a2023fd90d8"

        def install
          bin.install "dbh"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/genesisdayrit/dbharness/releases/download/v0.4.0/dbh_0.4.0_linux_arm64.tar.gz"
        sha256 "13560251e01682831c652db08c6fbdfd1a7b3ae7137d9c79566c434c39ec517f"

        def install
          bin.install "dbh"
        end
      end
    end
  end

  test do
    system "#{bin}/dbh", "init", "--help"
  end
end
