# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbharness < Formula
  desc "DB Harness project initializer"
  homepage "https://github.com/genesisdayrit/dbharness"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/genesisdayrit/dbharness/releases/download/v0.1.1/dbharness_0.1.1_darwin_amd64.tar.gz"
      sha256 "cfd3f4c67e9facbcb69c4cdfe71f3ffa8d6ffe1a89c95d1d0cdfa815347f8b75"

      def install
        bin.install "dbharness"
      end
    end
    on_arm do
      url "https://github.com/genesisdayrit/dbharness/releases/download/v0.1.1/dbharness_0.1.1_darwin_arm64.tar.gz"
      sha256 "09f3430d3bfa2775fd459af8bffd5bda36a56b08c65628a6572656689c72e608"

      def install
        bin.install "dbharness"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/genesisdayrit/dbharness/releases/download/v0.1.1/dbharness_0.1.1_linux_amd64.tar.gz"
        sha256 "e8885b45c7eb2609b3e1873988ed9d9fb12bfc5e0f533f63a6b771b406c61265"

        def install
          bin.install "dbharness"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/genesisdayrit/dbharness/releases/download/v0.1.1/dbharness_0.1.1_linux_arm64.tar.gz"
        sha256 "4c86c9355bfff417955f8b4cbe3dd1fe4b100b33588cc6a154dd8de17b92ad17"

        def install
          bin.install "dbharness"
        end
      end
    end
  end

  test do
    system "#{bin}/dbharness", "init", "--help"
  end
end
